---
- name: Create
  hosts: localhost
  connection: local

  tasks:
    - name: Set variables of molecule.yml to molecule_platforms
      ansible.builtin.set_fact:
        molecule_platforms: "{{ molecule_yml.platforms }}"

    - name: Create a network
      community.docker.docker_network:
        name: "{{ molecule_platforms.0.networks }}"

    - name: Setup GoAccess container
      community.docker.docker_container:
        name: "{{ molecule_platforms.0.name }}"
        command: /sbin/init
        detach: yes
        image: "{{ molecule_platforms.0.image }}"
        networks:
          - name: "{{ molecule_platforms.0.networks }}"
        privileged: yes
        ports:
          - "80:80"
        state: started
        tty: yes

    - name: Setup Selenium container
      community.docker.docker_container:
        name: "{{ molecule_platforms.1.name }}"
        image: "{{ molecule_platforms.1.image }}"
        networks:
          - name: "{{ molecule_platforms.1.networks }}"
        ports:
          - "4444:4444"
        state: started
