---
- name: Prepare
  hosts: all
  become: true

  roles:
    - mamono210.httpd_install
    - mamono210.epel
    - mamono210.goaccess_install

  tasks:
    - name: Put SELinux in permissive mode.
      ansible.posix.selinux:
        policy: targeted
        state: permissive
