---
- name: Prepare
  hosts: goaccess
  connection: docker
  become: true
  vars:
    ansible_user: ansible
  roles:
    - mamono210.httpd_install
    - mamono210.epel
    - mamono210.goaccess_install
