---
- name: Side effect
  gather_facts: false
  hosts: localhost

  tasks:
    - name: Execute selenium for creating httpd access_log
      ansible.builtin.command:
        cmd: python access.py
      args:
        chdir: files
      changed_when: false
      delegate_to: localhost
